# Generated by Django 3.2.9 on 2022-01-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('no_category', 'No Category'), ('world_wide', 'World Wide'), ('technology', 'Technology'), ('design', 'Design'), ('culture', 'Culture'), ('business', 'Business'), ('politics', 'Politics'), ('science', 'Science'), ('life_style', 'Life Style'), ('travel', 'Travel')], default='no_category', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
