# Generated by Django 3.2.9 on 2022-01-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20220113_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('no_category', 'No Category'), ('technology', 'Technology'), ('culture', 'Culture'), ('business', 'Business'), ('science', 'Science'), ('life_style', 'Life Style'), ('travel', 'Travel')], default='no_category', max_length=50),
        ),
    ]